---
title: "Aqui você encontra conteúdos e publicações sobre Ciência de Dados"
subtitle: É uma extensão do café com R - Para divulgar e ensinar programação em R.
listing:
  contents: posts
  type: default
  image-align: left
  categories: true
  fields:
    - image
    - title
    - description
    - date
    - author
    - categories
page-size: 5
---

:::: {style="margin-bottom: 40px;"}
::: texto-justificado
### Como salvar essa apresentação em PDF

Você também pode salvar esta apresentação diretamente em PDF usando o modo PDF Export Mode do próprio visualizador do Quarto (**`menu lateral > Tools > PDF Export Mode`**). Isso ajusta automaticamente os slides para um formato adequado de impressão.

Além disso, esta apresentação ficará disponível online no meu site, permitindo que você acesse quando quiser.

### Aulas no GitHub

Todo o material, incluindo o arquivo .qmd, o tema visual e os códigos utilizados está no meu GitHub, para que você possa reproduzir, adaptar ou integrar às suas próprias aulas e projetos com total liberdade.

Acesse apresentações: <https://github.com/JenniferLopes/meu_site>

<br>
:::
::::

### ☕ Café com R

> Que cada **gole** desperte uma nova ideia.
>
> Que cada **script** abra uma nova conversa.
>
> Que o **Café com R**, se torne um ponto de encontro nosso!

```{=html}
<iframe    src="newsletter-widget.html"    width="100%"    height="800"    frameborder="0"    scrolling="no"   style="border:none; display:block; margin: 0 auto;"> </iframe>
```
